services:
  - type: web
    name: mindcare-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.9"
      - key: FOURSQUARE_API_KEY
        value: ""
      - key: JWT_SECRET_KEY
        value: ""
      - key: MONGO_URI
        value: ""
